name: qrcode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.6
  lottie: ^3.1.2
  open_file_plus: ^3.4.1+1
  path_provider: ^2.1.3
  pdf: ^3.11.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
  uses-material-design: true
